/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jmary.perguntas_e_respostas_por_assunto;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.security.CodeSource;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;
import java.util.zip.ZipEntry;
import java.util.zip.ZipInputStream;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author admin
 */
public class Visualizador_Interno_Desafios extends javax.swing.JPanel {
    
    String s = System.getProperty("file.separator");
    String internalStorageDir = System.getProperty("user.dir");

    String nome_do_pacote_endereco_Iterno_Do_Assunto = System.getProperty("user.dir") + "\\00_Externo\\";      
    int img_Atual = 0;
    
    int largura = 0;
    int altura = 0;
    
    JTabbedPane tabAssunto_Recebido;
    
    Home Home;
    
    String nome_Arquivo = "";
    
    List<String> listaDosArquivos = new ArrayList<String>();
    Class Classe_Das_Imagens = null;
    /**
     * Creates new form Visualizador_Interno2
     * @param Home2
     * @param tabAssunto_Recebido2
     * @param Classe_Das_Imagens2
     * @param img_Atual2
     * @param endereco_Externo_da_Pasta2
     * @param largura2
     * @param altura2
     */
    public Visualizador_Interno_Desafios( Home Home2, JTabbedPane tabAssunto_Recebido2, Class Classe_Das_Imagens2, int img_Atual2, String endereco_Externo_da_Pasta2, int largura2, int altura2 ) {
        initComponents();
        
        Home = Home2;
        
        tabAssunto_Recebido = tabAssunto_Recebido2;
        
        Classe_Das_Imagens = Classe_Das_Imagens2;
        
        img_Atual = img_Atual2;
        nome_do_pacote_endereco_Iterno_Do_Assunto = endereco_Externo_da_Pasta2;
        
        largura = largura2;
        altura = altura2;
        
        jSlider1.setValue(0);
        setarPastaInicio(img_Atual2);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfPagina = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        lbConteudo_Online = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jmary/perguntas_e_respostas_por_assunto/imagens_internas/pdf_16_16.gif"))); // NOI18N
        jLabel12.setToolTipText("GERAR ARQUIVO PDF");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.setEnabled(false);
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel12MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel12MouseReleased(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jmary/perguntas_e_respostas_por_assunto/imagens_internas/FonteAum.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.setEnabled(false);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jmary/perguntas_e_respostas_por_assunto/imagens_internas/laranja_anterior.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.setEnabled(false);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jmary/perguntas_e_respostas_por_assunto/imagens_internas/laranja_proximo.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel10MousePressed(evt);
            }
        });

        tfPagina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPaginaActionPerformed(evt);
            }
        });

        jLabel6.setText("Ir Para");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jmary/perguntas_e_respostas_por_assunto/imagens_internas/laranja_home.png"))); // NOI18N
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.setEnabled(false);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jmary/perguntas_e_respostas_por_assunto/imagens_internas/laranja_proximo.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.setEnabled(false);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel5MousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jmary/perguntas_e_respostas_por_assunto/imagens_internas/FonteDim.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.setEnabled(false);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jmary/perguntas_e_respostas_por_assunto/imagens_internas/FontePadrao.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.setEnabled(false);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel14MousePressed(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jmary/perguntas_e_respostas_por_assunto/imagens_internas/16_chrome.png"))); // NOI18N
        jLabel13.setToolTipText("GERAR ARQUIVO HTML");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabel13MouseReleased(evt);
            }
        });

        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(10, 10, 10)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(34, 34, 34)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(58, 58, 58)
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(tfPagina))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9, tfPagina});

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lbConteudo_Online.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbConteudo_Online.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbConteudo_Online.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/jmary/perguntas_e_respostas_por_assunto/imagens_internas/anao.gif"))); // NOI18N
        lbConteudo_Online.setToolTipText("");
        lbConteudo_Online.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(">>");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("<<");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbConteudo_Online, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(lbConteudo_Online, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MousePressed
        /*
        img_Atual = 0; try{ img_Atual = Integer.parseInt( tfPagina.getText().trim() ); }catch(Exception e){}
        new Thread() {   @Override public void run() { try { //Thread.sleep( 1 );
            Exportando = new Exportando("ABRINDO...");
            Exportando.setVisible(true);Exportando.pbg.setMinimum(0);
            Exportando.pbg.setMaximum( 100 );
            Exportando.pbg.setValue( 50 );
            
            tabAssunto_Recebido.removeTabAt( tabAssunto_Recebido.getSelectedIndex() );
            tabAssunto_Recebido.add(String.valueOf( img_Atual ), 
                    new Visualizador_Interno_Exercicios( Home, tabAssunto_Recebido, img_Atual, nome_do_pacote_endereco_Iterno_Do_Assunto, largura, altura) );

            Exportando.fechar();
        } catch( Exception e ){ Exportando.fechar(); e.printStackTrace(); } } }.start();
        */
    }//GEN-LAST:event_jLabel5MousePressed

    Exportando Exportando;
    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        if( jLabel1.isEnabled() == true ){
            
            jLabel1.setEnabled(false); 
   
            new Thread() {   @Override public void run() { try { //Thread.sleep( 1000 );
                
                //Se chegar no fim não recomeça do começo novamente por que é exercício.
                int vxAtual = qtdArquivos - 1;
                if( img_Atual < vxAtual ) {    
                
                    img_Atual++;
                    Home.jp_Letras_das_Respostas_Desafios.setVisible(true);
                    Home.lb_Reiniciar_Desafios.setVisible(false);
                    setarImagemInterna(img_Atual);
                }
                else{
                
                    img_Atual++;
                    Home.jp_Letras_das_Respostas_Desafios.setVisible(false);
                    Home.lb_Reiniciar_Desafios.setVisible(true);
                }
                              
            } catch( Exception e ){ 
                e.printStackTrace();
            } 
            finally{
                
                try{ Thread.sleep( 1000 ); } catch( InterruptedException e ){ }
                jLabel1.setEnabled(true); 
            } } }.start();         
        }
    }//GEN-LAST:event_jLabel1MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        /*
        img_Atual--;
        setarImagemInterna(img_Atual);
        
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );
            Exportando = new Exportando("ABRINDO...");
            Exportando.setVisible(true);Exportando.pbg.setMinimum(0);
            Exportando.pbg.setMaximum( 100 );
            Exportando.pbg.setValue( 50 );
            
            tabAssunto_Recebido.removeTabAt( tabAssunto_Recebido.getSelectedIndex() );
            tabAssunto_Recebido.add(String.valueOf( img_Atual ), 
                    new Visualizador_Interno_Exercicios( Home, tabAssunto_Recebido, img_Atual, nome_do_pacote_endereco_Iterno_Do_Assunto, largura, altura) );

            Exportando.fechar();
        } catch( Exception e ){ Exportando.fechar(); e.printStackTrace(); } } }.start();
        */
    }//GEN-LAST:event_jLabel2MousePressed

    private void tfPaginaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPaginaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPaginaActionPerformed

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        //largura -= 5;
        //altura -= 5;
        //setarPastaInicio(img_Atual);
    }//GEN-LAST:event_jLabel7MousePressed

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        //largura += 5;
        //altura += 5;
        //setarPastaInicio(img_Atual);
    }//GEN-LAST:event_jLabel8MousePressed

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        /*
        img_Atual--;        
        new Thread() {   @Override public void run() { try { //Thread.sleep( 1 );
            if( jLabel9.isEnabled() == true ){
                jLabel9.setEnabled(false);
                
                Exportando = new Exportando("ABRINDO...");
                Exportando.setVisible(true);Exportando.pbg.setMinimum(0);
                Exportando.pbg.setMaximum( 100 );
                Exportando.pbg.setValue( 50 );
            
                tabAssunto_Recebido.removeTabAt( tabAssunto_Recebido.getSelectedIndex() );
                tabAssunto_Recebido.add(String.valueOf( img_Atual ), 
                    new Visualizador_Interno_Exercicios( Home, tabAssunto_Recebido, img_Atual, nome_do_pacote_endereco_Iterno_Do_Assunto, largura, altura) );

                Exportando.fechar(); 
                jLabel9.setEnabled(true);
            }
        } catch( Exception e ){ 
            Exportando.fechar(); e.printStackTrace();
            jLabel9.setEnabled(true);
        } } }.start();
        */
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MousePressed
        if( jLabel10.isEnabled() == true ){
            
            jLabel10.setEnabled(false); 
   
            new Thread() {   @Override public void run() { try { //Thread.sleep( 1000 );
                
                //Se chegar no fim não recomeça do começo novamente por que é exercício.
                int vxAtual = qtdArquivos - 1;
                if( img_Atual < vxAtual ) {    
                
                    img_Atual++;
                    Home.jp_Letras_das_Respostas_Desafios.setVisible(true);
                    Home.lb_Reiniciar_Desafios.setVisible(false);
                    setarImagemInterna(img_Atual);
                }
                else{
                
                    img_Atual++;
                    Home.jp_Letras_das_Respostas_Desafios.setVisible(false);
                    Home.lb_Reiniciar_Desafios.setVisible(true);
                }
                              
            } catch( Exception e ){ 
                e.printStackTrace();
            } 
            finally{
                
                try{ Thread.sleep( 1000 ); } catch( InterruptedException e ){ }
                jLabel10.setEnabled(true); 
            } } }.start();         
        }
    }//GEN-LAST:event_jLabel10MousePressed

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed
        /*
        img_Atual=0;
        new Thread() {   @Override public void run() { try { //Thread.sleep( 1 );
            Exportando = new Exportando("ABRINDO...");
            Exportando.setVisible(true);Exportando.pbg.setMinimum(0);
            Exportando.pbg.setMaximum( 100 );
            Exportando.pbg.setValue( 50 );
            
            tabAssunto_Recebido.removeTabAt( tabAssunto_Recebido.getSelectedIndex() );
            tabAssunto_Recebido.add(String.valueOf( img_Atual ), 
                    new Visualizador_Interno_Exercicios( Home, tabAssunto_Recebido, img_Atual, nome_do_pacote_endereco_Iterno_Do_Assunto, largura, altura) );

            Exportando.fechar();
        } catch( Exception e ){ Exportando.fechar(); e.printStackTrace(); } } }.start();
        */
    }//GEN-LAST:event_jLabel11MousePressed

    private void jLabel12MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MousePressed
        /*
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );

            if( jLabel12.isEnabled() ){
                try{
                    jLabel12.setEnabled(false);
                    
                    JpgToPdf JpgToPdf = new JpgToPdf( nome_do_pacote_endereco_Iterno_Do_Assunto, "zz" );
                    JpgToPdf.JpgParaPdf();
                    
                    jLabel12.setEnabled(true);
                } catch( Exception e ){
                    jLabel12.setEnabled(true);
                }
            }
        } catch( Exception e ){ } } }.start();   
        */
    }//GEN-LAST:event_jLabel12MousePressed

    private void jLabel12MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel12MouseReleased

    String home_inicio = "";
    String nome_do_arquivo_gerado = "zz_desafios_html";
    String nome_da_pasta_das_imagens = "zz_desafios_html_imagens";
    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
       
        Object[] options = { "Confirmar", "Cancelar" };
        int n = JOptionPane.showOptionDialog( null, "Confirme a Opção para Gerar o Html. \n",
            "Gerar Arquivo em Html",
            JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0] );
        if(n==0){ 
        
        /*
        new Thread() {   @Override public void run() { try { Thread.sleep( 1 );

            if( jLabel13.isEnabled() ){
                try{
                    jLabel13.setEnabled(false);
                    
                    JpgToHtml JpgToHtml = new JpgToHtml( System.getProperty("user.dir")+"\\"+"00_Externo", "zz" );
                    JpgToHtml.JpgToHtml();
                    
                    jLabel13.setEnabled(true);
                } catch( Exception e ){
                    jLabel13.setEnabled(true);
                }
            }
        } catch( Exception e ){ } } }.start(); 
        */
        
        new Thread() {   @Override public void run() { try { //Thread.sleep( 1 );
            
            String titulo_do_assunto = Home.lb_titulo_do_assunto.getText().trim();
            
            Exportando = new Exportando("Gerando HTML...");
            Exportando.setVisible(true);Exportando.pbg.setMinimum(0);
            Exportando.pbg.setMaximum( listaDosArquivos.size() );
            //Exportando.pbg.setValue( 50 );
            
            // Endereço do Arquivo
            String endereco_arquivo_html = internalStorageDir + s + nome_do_arquivo_gerado + ".html";
            // Criar arquivo
            File file = new File( endereco_arquivo_html );
            // Se o arquivo nao existir, ele gera
            if (!file.exists()) {
                // Se o Arquivo não existir este método criar o arquivo
                //Arquivo_Ou_Pasta.criar_Arquivo_Iso_Boo_Tipo_UTFISO( endereco_arquivo, "", "UTF-8");  
                file.createNewFile();
            }
            else{
                
                // Se o Arquivo existir este método deleta o arquivo
                Arquivo_Ou_Pasta.deletar( new File( endereco_arquivo_html ) );
                
                // Após deletar o arquivo este método criar o arquivo novamente
                //Arquivo_Ou_Pasta.criar_Arquivo_Iso_Boo_Tipo_UTFISO( endereco_arquivo, "", "UTF-8");  
                file.createNewFile();
            }
            
            // Endereço do Arquivo
            String endereco_pasta_imagens = internalStorageDir + s + nome_da_pasta_das_imagens;
            // Criar pasta
            File pasta = new File( endereco_pasta_imagens );
            // Se a pasta nao existir, ele gera
            if (!pasta.exists()) {
                // Se a pasta não existir este método criar o arquivo
                Arquivo_Ou_Pasta.criarPasta( internalStorageDir, nome_da_pasta_das_imagens );   
            }
            else{
                
                // Se a pasta existir este método deleta a pasta
                Arquivo_Ou_Pasta.deletar( new File( endereco_pasta_imagens ) ); 
                
                // Se a pasta não existir este método criar o arquivo
                Arquivo_Ou_Pasta.criarPasta( internalStorageDir, nome_da_pasta_das_imagens );   
            }
            
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "<html>" );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "<head>" );
            
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "<title>" );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "JMarySystems: " + titulo_do_assunto );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "</title>" );
            
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "<meta name=\"title\" property=\"og:title\" content= '" );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "JMarySystems: " + titulo_do_assunto );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "' >" );
            
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "<meta name=\"image\" property=\"og:image\" content= '" );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "https://www.jmarysystems.com.br/web/Perguntas_e_Respostas/Informatica/ADS/0007_Des_para_Disp_Moveis/unidade_01/zz_magens_fixas/inicio.PNG"  );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "' >" );
            
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "<meta name=\"description\" property=\"og:description\" content= '" );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "Desafios - " + titulo_do_assunto + " - Espaço reservado para Perguntas e Respostas / Leitura e Aprendizagem - Informática, Português, Matemática, Física, Química, Biologia, Geografia, História, Filosofia..."  );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "' >" );
            
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "<style>" );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "body { -webkit-print-color-adjust: exact; }" );
            
            //Dentro do head / style
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, 
"@media (min-width : 980px) {" +
"    /*topo*/" +
"        .crtl_de_certo_ou_errado_cima{ width: 100px; height: 14px; }" +
"        .crtl_imagem{ position: absolute; width: 100%; height: 92%; }" +
"    /*topo*/" +
"}" +
"@media (min-width : 980px) and (max-width : 1024px) {" +
"    /*topo*/" +
"        .crtl_de_certo_ou_errado_cima{ width: 100px; height: 14px; }" +
"        .crtl_imagem{ position: absolute; width: 100%; height: 92%; }" +
"    /*topo*/    " +
"}\n" +
"@media (max-width : 980px) {" +
"    /*topo*/" +
"        .crtl_de_certo_ou_errado_cima{ width: 100px; height: 14px; }" +
"        .crtl_imagem{ position: absolute; width: 100%; height: 92%; }" +
"    /*topo*/" +
"}" +
"@media (max-width : 570px) { " +
"    /*topo*/" +
"        .crtl_de_certo_ou_errado_cima{ width: 65px; height: 13px; }" +
"        .crtl_imagem{ position: inherit; width: 100%; height: 92%; }" +
"    /*topo*/" +
"}" +
"@media (max-width : 418px) {" +
"    /*topo*/" +
"        .crtl_de_certo_ou_errado_cima{ width: 50px; height: 10px; }" +
"        .crtl_imagem{ position: inherit; width: auto; height: auto; }" +
"    /*topo*/" +
"}" 
            );
            
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "</style>" );
                                   
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "</head>" );
            
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "<body " );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, 
                    "style=\"width: 100%; height: 100%; padding: 0; margin: 0; background-color: #F5F5F5;" +
"               font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: black; line-height: 1.5;\" " +
"        onload='letra(&apos;corpo&apos;); setar_img_inicial();'" 
            );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, " >" );
            
            
            
            
//  script início   ##########################################################################       
    // Iniciando script
    Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n\n <script type=\"text/javascript\"> " );
    
        //Variáveis globais
        Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, 
            "\n\n  var assuntodoexercicio = '" + nome_do_pacote_endereco_Iterno_Do_Assunto + "'; " +
            "\n var exeatual = 0; " +
            "\n var qtdacertos = 0; " +
            "\n var qtdaerros = 0; " +
            "\n var pasta = '" + nome_da_pasta_das_imagens + "'; \n\n" 
        ); 
        
        //Variáveis globais
        for(int i = 0; i < listaDosArquivos.size(); i++ ){
            Exportando.pbg.setValue( i );

            //////////////////////////////////////////////////////////////////////////////////////////////  
            BufferedImage bufImg = null;
            ImageIcon     icon   = null;
            Image         image  = null;
            try{
                bufImg = ImageIO.read(Classe_Das_Imagens.getResource( listaDosArquivos.get( i ) ) );
                icon   = new ImageIcon(bufImg);
                image  = icon.getImage();//ImageIO.read(f);  
            } catch (IOException ex) {}  

            try {  
                    
                image = icon.getImage();//ImageIO.read(f);  
                int widith = image.getWidth(icon.getImageObserver() ) + largura;
                int height = image.getHeight(icon.getImageObserver() )+ altura;
                    
            }catch(Exception ex){}
               
            File f = new File( listaDosArquivos.get( i ) );
            String nome = f.getName();
            String nomeList[] = nome.split(Pattern.quote("."));
            ImageIO.write( bufImg, nomeList[1], new File( endereco_pasta_imagens + s + nome ) );
            String xcxc[] = nomeList[0].split( "@" );
            //////////////////////////////////////////////////////////////////////////////////////////////                

            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, 
                "\n  var exe" + i + " = new Array( '" + nome_da_pasta_das_imagens + "/" + nome + "',  '" + nome_da_pasta_das_imagens + "/" + nome +"', '" + xcxc[1] + "' ); " 
            );
        }
    
        //Função
        Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n\n function iniciar() { " );
        
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n mostrarocultar('bt0'); " );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n mostrarocultar('bt2'); " );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById('nomedesteexercicio').innerHTML = ''; " );
            //Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo, "\n exeatual++; " );
            //Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo, "\n alert( exeatual ); " );
        
            //Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo, "\n alert( exe0[0] ); " );        
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById('audio_mouse_encima').play(); " );            
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById('centroexe').src = exe0[0]; " );
                                    
        Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n } " );
        
        //Função
        Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n\n function proximo( exeR ) { " );
        
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById('audio_mouse_encima').play(); " );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById('centroexe').src = exeR[0]; " );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n mostrarocultar('bt1'); " );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n mostrarocultar('bt2'); " );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById('nomedesteexercicio').innerHTML = ''; " );
                        
        Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n } " );
        
        //Função
        Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n\n function resposta( exeR ) { " );
        
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n var x = document.getElementById(\"abcdresposta\").value; " );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n if( x === exeR[2] ){ " );
                Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById('audio_acerto').play(); " );
                Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById('centroexe').src =exeR[1];  " );
                Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n qtdacertos++; " );
                Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById('tdacertos').innerHTML = qtdacertos;  " );
                Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById('nomedesteexercicio').innerHTML = \"Parabéns Resposta Correta - Opção: \" + exeR[2]; " );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n } " );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n else{ " );
                Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById('audio_erro').play(); " );
                Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById('centroexe').src =exeR[1];   " );
                Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n qtdaerros++; " );
                Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById('tderros').innerHTML = qtdaerros; " );
                Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById('nomedesteexercicio').innerHTML = \"Resposta Incorreta - a correta seria à opção: \" + exeR[2]; " );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n } " );
            
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById( 'selectdaresposta' ).className += \"dispnone\"; " );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById( 'bt1' ).removeAttribute( \"class\", \"dispnone\" ); " );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById( 'bt2' ).className += \"dispnone\"; " );
                        
        Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n } " );
        
        //Função
        Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n\n function abcdResposta( abcdR ) { " );
        
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById(\"abcdresposta\").value = abcdR; " );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n mostrarocultar('bt1'); " );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n mostrarocultar('bt2'); " );
        Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, " } " ); 
        
        //Função
        Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n\n function mostrarocultar( id ) { " );
        
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n if( document.getElementById(id).style.display === 'none' ){ " );
                Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById(id).style.display = 'block'; " ); 
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n } " );
            
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n else{ " );
                Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById(id).style.display = 'none'; " ); 
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n } " ); 
        Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n } " ); 
        
        //Função
        Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n\n function setar_img_inicial() { " );
        
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById('centroexe').src ='zz_magens_fixas/inicio.PNG';" );
        Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n } " ); 
        
        //Função
        Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n\n function proximoexecombase( x ) { " );
        
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n document.getElementById('audio_mouse_encima').play(); " );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n if( x === 'p' ){ exeatual++; } " );
            
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n switch( exeatual ) { " );
            
                for(int i = 0; i < listaDosArquivos.size(); i++ ){
                    Exportando.pbg.setValue( i );

                    //////////////////////////////////////////////////////////////////////////////////////////////  
                    BufferedImage bufImg = null;
                    ImageIcon     icon   = null;
                    Image         image  = null;
                    try{
                        bufImg = ImageIO.read(Classe_Das_Imagens.getResource( listaDosArquivos.get( i ) ) );
                        icon   = new ImageIcon(bufImg);
                        image  = icon.getImage();//ImageIO.read(f);  
                    } catch (IOException ex) {}  

                    try {  
                    
                        image = icon.getImage();//ImageIO.read(f);  
                        int widith = image.getWidth(icon.getImageObserver() ) + largura;
                        int height = image.getHeight(icon.getImageObserver() )+ altura;
                    
                    }catch(Exception ex){}
               
                    File f = new File( listaDosArquivos.get( i ) );
                    String nome = f.getName();
                    String nomeList[] = nome.split(Pattern.quote("."));
                    //ImageIO.write( bufImg, nomeList[1], new File( endereco_pasta + s + nome ) );
                    //String xcxc[] = nomeList[0].split( "@" );
                    //////////////////////////////////////////////////////////////////////////////////////////////                

                    Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, 
                        "\n  case " + i +": if( x === 'p' ){ proximo( exe" + i + " ); } else{ resposta( exe" + i + " ); }  break; " 
                    );
                }
                
                Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, 
                    "\n\n default:     " +
"\n                        document.getElementById('nomedesteexercicio').innerHTML = \"FIM - \" + assuntodoexercicio;" +
"\n                        document.getElementById( 'bt1' ).className += \"dispnone\";" +                                                               
"\n                        document.getElementById('centroexe').src ='zz_magens_fixas/fim.PNG';" +
"\n                        mostrarocultar('img_home');    " +
"\n                        mostrarocultar('bt1');  " 
            );
                
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n } " ); 
            
        Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n } " ); 
        
    Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "\n\n </script> " );
//   script início   ##########################################################################            
 

















Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, 
"\n <table width=\"100%\" cellpadding=\"1\" cellspacing=\"1\" border=\"0\" style=\"margin: 0px; padding: 0px;\">" +
"\n     <tr>" +
"\n         <td align=\"center\" valign=\"center\" width=\"100%\" style=\"margin: 0px; padding: 0px; background-color: #3A3A3A; font-family: Arial, Helvetica, sans-serif; font-size: 14px; color: #ffffff; \"> " +
                titulo_do_assunto +

"        </td> " +
"    </tr> " +
"</table>" 
); 
            
            
       
            
            
            
            
       












Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, 
"<input type=\"hidden\" id=\"abcdresposta\" value=\"Z\">" +
"" +



"\n <table width=\"100%\" height=\"8%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"margin: 0px; padding: 0px;\">" +
"\n     <tr>" +
"\n         <td width=\"100%\" height=\"8%\" style=\"margin: 0px; padding: 0px; background-color: #3A3A3A;\"> " +
"\n             " +
"\n             <table width=\"100%\" height=\"100%\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"margin: 0px; padding: 0px;\">" +
"\n                 <tr>" +
"\n                     <td style=\"margin: 0px; padding: 0px;\" align=\"center\" valign=\"center\">" +
"\n                         <img id=\"img_home\" " +
"\n                             style=\"display: none; margin: 0px; padding: 0px; height: 90%; width: 30px; cursor: pointer;\"" +
"\n                             src=\"zz_magens_fixas/casa.png\"             " +
"\n                             onmouseover=\"this.src='zz_magens_fixas/casa.png'\" " +
"\n                             onmouseout=\"this.src='zz_magens_fixas/casa.png'\"" +
"\n                             onClick=\" (function(){ window.location.reload() })() \"" +
"\n                         > " +
"\n                     </td>  " +
"\n                     <td style=\" margin: 0px; padding: 0px; padding-left: 1px;\" align=\"center\" valign=\"center\">" +
"\n                         <button id=\"bt0\" type=\"button\" " +
"\n                             style=\"height: 90%; font: bold normal 100% verdana,arial,helvetica;\" " +
"\n                             onclick=\"iniciar();\">" +
"\n                         Iniciar</button> " +
"\n                     </td>   " +
"\n                     <td style=\"margin: 0px; padding: 0px;\" align=\"center\" valign=\"center\"> " +
"\n                         <button id=\"bt1\" type=\"button\" " +
"\n                                 style=\"height: 90%; display: none; font: bold normal 100% verdana,arial,helvetica;\" " +
"\n                                 onclick=\"proximoexecombase( 'p' )\">" +
"\n                             Próximo</button> " +
"\n                     </td> " +
"\n                 <td id=\"bt2\" style=\"display: none; height: 100%;\"> " +
"\n                     <ul style=\"list-style:none; padding: 0px; margin: 0px; height: 100%;\" >" +
        
"\n                         <li style=\"float: left; padding-left: 3px; padding-right: 15px;\">" +
"\n                             <button type=\"button\" " +
"\n                                         style=\"width: 100%; height: 100%; cursor:pointer; font: bold normal 100% verdana,arial,helvetica;\" " +
"\n                                         onclick=\"abcdResposta( 'A' ); proximoexecombase( 'r' )\">" +
"\n                                     A</button>" +
"\n                         </li>" +
"\n                         <li style=\"float: left; padding-left: 3px; padding-right: 15px;\">" +
"\n                             <button type=\"button\" " +
"\n                                         style=\"width: 100%; height: 100%; cursor:pointer; font: bold normal 100% verdana,arial,helvetica;\" " +
"\n                                         onclick=\"abcdResposta( 'B' ); proximoexecombase( 'r' )\">" +
"\n                                     B</button>" +
"\n                         </li>" +
"\n                         <li style=\"float: left; padding-left: 3px; padding-right: 15px;\">" +
"\n                             <button type=\"button\" " +
"\n                                        style=\"width: 100%; height: 100%; cursor:pointer; font: bold normal 100% verdana,arial,helvetica;\" " +
"\n                                         onclick=\"abcdResposta( 'C' ); proximoexecombase( 'r' )\">" +
"\n                                     C</button> " +
"\n                         </li>" +
"\n                         <li style=\"float: left; padding-left: 3px; padding-right: 15px;\">" +
"\n                             <button type=\"button\" " +
"\n                                        style=\"width: 100%; height: 100%; cursor:pointer; font: bold normal 100% verdana,arial,helvetica;\" " +
"\n                                        onclick=\"abcdResposta( 'D' ); proximoexecombase( 'r' )\">" +
"\n                                    D</button> " +
"\n                         </li>" +
"\n                         <li style=\"float: left; padding-left: 3px; \">" +
"\n                             <button type=\"button\" " +
"\n                                        style=\"width: 100%; height: 100%; cursor:pointer; font: bold normal 100% verdana,arial,helvetica;\" " +
"\n                                        onclick=\"abcdResposta( 'E' ); proximoexecombase( 'r' )\">" +
"\n                                    E</button> " +
"\n                         </li>" +        
"                        " +
"                    </ul>" +
"   " +
"                </td> " +
"                " +
"                <td id=\"nomedesteexercicio\" style=\"margin: 0px; padding: 0px; font-family: Arial, Helvetica, sans-serif; font-size: 100%; color:#FFFFFF;\" align=\"left\" valign=\"center\">" +
"                    Nível 02 - Desafios " +
"                </td> " +
"                                    " +
"                <td style=\"margin: 0px; padding: 0px; padding-right: 3px; height: 100%;\" align=\"right\" valign=\"center\">" +
"                        <div style=\"padding: 0px; margin: 0px; height: 100%;\">" +
"                            <table align=\"right\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"height: 100%; margin: 0px; padding: 0px; box-shadow: 0 0 10px #222;\">" +
"        " +
"                                <tr>" +
"                                    <td style=\"padding: 0px; margin: 0px; height: 100%;\">" +
"                " +
"                                        <table border=\"0\" cellpadding=\"2\" cellspacing=\"0\" " +
"                                            style=\"float: right; position:relative; border: 1px solid black; margin: 0px; padding: 0px\" class=\"mr3\">" +
"                                            <tbody>" +
"                                            <tr>" +
"                                                <td class=\"crtl_de_certo_ou_errado_cima\" bgcolor=\"#C10033\" style=\"color:#FFFFFF; font-size: 100%;\" align=\"center\">_ERROS_</td>" +
"                                            </tr>" +
"                                            <tr>" +
"                                                <td bgcolor=\"#F1EEED\" align=\"center\" style=\"height: 18px;\" >" +
"                                                    <table cellpadding=\"1\" cellspacing=\"1\" border=\"0\" align=\"center\">" +
"                                                        <tbody><tr>" +
"                                                            <td id=\"tderros\" align=\"center\" style=\"font: bold normal 100% verdana,arial,helvetica;\">" +
"                                                                0" +
"                                                            </td>" +
"                                                        </tr>" +
"                                                    </tbody></table>" +
"                                                </td>" +
"                                            </tr>" +
"                                            </tbody></table>" +
"                \n" +
"                                    </td>    " +
"            \n" +
"                                    <td style=\"padding: 0px; margin: 0px; height: 100%;\">" +
"                \n" +
"                                        <table border=\"0\" cellpadding=\"2\" cellspacing=\"0\" " +
"                                            style=\"float: right; position:relative; border: 1px solid black; margin: 0px; padding: 0px\" class=\"mr3\">" +
"                                            <tr>" +
"                                                <td class=\"crtl_de_certo_ou_errado_cima\" bgcolor=\"#008000\" style=\"color:#FFFFFF; font-size: 100%;\" align=\"center\">ACERTOS</td>" +
"                                            </tr>" +
"                                           <tr>" +
"                                               <td bgcolor=\"#F1EEED\" align=\"center\" style=\"height: 18px;\">" +
"                                                   <table cellpadding=\"1\" cellspacing=\"1\" border=\"0\" align=\"center\">" +
"                                                        <tbody><tr>" +
"                                                            <td id=\"tdacertos\" align=\"center\" style=\"font: bold normal 100% verdana,arial,helvetica;\">" +
"                                                                0" +
"                                                            </td>" +
"                                                        </tr>" +
"                                                    </tbody></table>" +
"                                                </td>" +
"                                            </tr>" +
"                                        </table>" +
"                " +
"                                    </td>" +
"            " +
"                                </tr>" +
"         " +
"    </table>" +
"                        </div>" +
"                    </td> " +
"                      " +
"                </tr>" +
"            </table>" +
"            " +
"        </td> " +
"    </tr> " +
"    " +
        
        /*
"    <tr>" +
"        <td width=\"100%\" height=\"100%\" style=\"margin: 0px; padding: 0px;\"> " +
"            <div style=\"margin: 0px; padding: 0px; width: 100%; height: 100%;\">" +
"                <img id=\"centroexe\" class=\"crtl_imagem\" alt=\"\" " +
"                    src= 'zz_magens_fixas/inicio.PNG' " +
"                > " +
"            </div>" +
"        </td> " +
"    </tr> " +
        */
                       
        
"</table>" +
"<!-- " +
"-0" +
"-1" +
"-2" +
"- #### TUDO FIM #### --> " +
"<!-- " +
"-0" +
"-1" +
"-2    " +
"-->" +
"" +
"" +
"        <audio id=\"audio_acerto\" controls style=\"display: none; padding: 0; margin: 0;\"> " +
"            " +
"            <source src=\"zz_magens_fixas/acerto.mp3\" type=\"audio/mpeg\">" +
"        </audio>" +
"       " +
"        <audio id=\"audio_erro\" controls style=\"display: none; padding: 0; margin: 0;\"> " +
"            " +
"            <source src=\"zz_magens_fixas/erro.mp3\" type=\"audio/mpeg\">" +
"        </audio>" +
"" +
"        <audio id=\"audio_mouse_encima\" controls style=\"display: none; padding: 0; margin: 0;\"> " +
"            " +
"            <source src=\"zz_magens_fixas/MouseEncima.mp3\" type=\"audio/mpeg\">" +
"        </audio> " 
            );  



Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "</table>" );



    Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, 
"         <img id=\"centroexe\" class=\"___crtl_imagem\" alt=\"\"  style=\"margin: 0px; padding: 0px;\"   " +
"             src= 'zz_magens_fixas/inicio.PNG' " +
"         > " 
    );
                        
            
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "</body>" );
            Arquivo_Ou_Pasta.escrever_Em_Arquivo_Boo( endereco_arquivo_html, "</html>" );
                       
            ////////////////////////////////////////////////////////////////////
            java.awt.Desktop.getDesktop().open( new File( endereco_arquivo_html ) );
            Exportando.fechar();
        } catch( Exception e ){             
            e.printStackTrace(); 
        } finally{
            Exportando.fechar(); 
        } } }.start();

        
}        
    }//GEN-LAST:event_jLabel13MousePressed

    private void jLabel13MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseReleased

    private void jLabel14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MousePressed
        //largura = 0;
        //altura = 0;
        //setarPastaInicio(img_Atual);
    }//GEN-LAST:event_jLabel14MousePressed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
                
        new Thread() {   @Override public void run() { try { //Thread.sleep( 1 );
            
            largura = jSlider1.getValue();
            altura = jSlider1.getValue();
            setarPastaInicio(img_Atual);
                              
        } catch( Exception e ){ 
            e.printStackTrace(); 
        } 
        finally{

        }
        } }.start(); 
    }//GEN-LAST:event_jSlider1StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel lbConteudo_Online;
    private javax.swing.JTextField tfPagina;
    // End of variables declaration//GEN-END:variables
         
    int      qtdArquivos;
    private void setarPastaInicio(int img_Atual_x){ 

        try { 
            
            CodeSource src = getClass().getProtectionDomain().getCodeSource();
            URL jar = src.getLocation();
            //System.out.println( "URL jar = src.getLocation();  -  " + jar );
            List<String> list = new ArrayList<String>();
            ZipInputStream zip = new ZipInputStream( jar.openStream() );
            ZipEntry ze = null;
            
            while( ( ze = zip.getNextEntry() ) != null ) {
                String entryName = ze.getName(); 
                
                String nomeList[] = entryName.split("/");  
                if( nomeList[0].trim().equalsIgnoreCase( nome_do_pacote_endereco_Iterno_Do_Assunto ) ){
                    
                    try{
                        if( nomeList[1].trim().equalsIgnoreCase("Desafios") ){
                        
                            if( entryName.endsWith(".JPG") || entryName.endsWith(".jpg") || entryName.endsWith(".PNG") || entryName.endsWith(".png") ) {
                        
                                try{ list.add( nomeList[2].trim() ); } catch( Exception e ){  }
                                //System.out.println( "entryName - " + entryName + " - nomeList[1]" + nomeList[1].trim());
                                //try{ System.out.println( "entryName - " + entryName + " - nomeList[2] - " + nomeList[2].trim()); } catch( Exception e ){  }
                            }
                        }
                    } catch( Exception e ){  }
                }
            }
            
            listaDosArquivos = list;
            qtdArquivos = listaDosArquivos.size();
            
            setarImagemInterna(img_Atual_x);
        } catch( Exception e ){ } 
    }
    
    public void setarImagemInterna( int img_AtualRecebida ){ 
        //img_Atual = img_Atual2;
        
        /*new Thread() {   @Override public void run() {*/ try { //Thread.sleep( 1 );

                if( (img_AtualRecebida < qtdArquivos) && (img_AtualRecebida >= 0) ){

                    BufferedImage bufImg = null;
                    ImageIcon     icon   = null;
                    Image         image  = null;
                    try{
                        bufImg = ImageIO.read(Classe_Das_Imagens.getResource( listaDosArquivos.get( img_AtualRecebida ) ) );
                        icon   = new ImageIcon(bufImg);
                        image  = icon.getImage();//ImageIO.read(f);  
                    } catch (IOException ex) {}  

                    try {  
                        image = icon.getImage();//ImageIO.read(f);  
                        int widith = image.getWidth(icon.getImageObserver() ) + largura;
                        int height = image.getHeight(icon.getImageObserver() )+ altura;
                                                                        
                        lbConteudo_Online.setIcon(new ImageIcon(image.getScaledInstance(
                            widith, height, Image.SCALE_DEFAULT)));
                        
                        try{
                                                        
                            jSlider1.setMaximum (widith);  
                            //jSlider1.setMinimum  (widith/10);  
                            jSlider1.setMinimum  (0);  
                            
                            /*
                            jSlider1.setMajorTickSpacing(widith/10); 
                            jSlider1.setMinorTickSpacing(2);                              
                            
                            jSlider1.setPaintTrack(true);
                            jSlider1.setPaintTicks(true);  
                            jSlider1.setPaintLabels(true);
                            */
                            
                        } catch (Exception ex) {}   
                       
                    }catch(Exception ex){}
                    
                    //Home.jPanel4.setVisible(true);
                    int vAtual = img_AtualRecebida + 1;
                    Home.lb_Status_Resposta_Desafios.setText( "Desafio: " + vAtual + " de: " + qtdArquivos );
                
                    String nome = listaDosArquivos.get( img_AtualRecebida ); //System.out.println("\n\n 111 - nome - " + nome);
                    String nomeList[] = nome.split(Pattern.quote(".")); //PEGAR EXTENSÃO
                    
                    try{ nome_Arquivo = nomeList[0]; } catch (Exception ex) {} //System.out.println("\n\n 222 - nome_Arquivo - " + nome_Arquivo); 
                    
                    String nomeList2[] = nome_Arquivo.split("@");                    
                    try{ Home.resposta_correta_do_desafio_atual = nomeList2[1]; } catch (Exception ex) {} //System.out.println("\n\n 333 - Home.resposta_correta_do_exercicio_atual - " + Home.resposta_correta_do_exercicio_atual);  
                
                }
                //Se chegar no fim não recomeça do começo novamente por que é exercício.
                /*
                else{   
                    if( img_Atual <= 0){
                        int qtd_Arquivos_da_Pasta = qtdArquivos-1;
                        img_Atual = qtd_Arquivos_da_Pasta;
                    }
                    else{
                        img_Atual = 0;
                    }

                    BufferedImage bufImg = null;
                    ImageIcon     icon   = null;
                    Image         image  = null;
                    try{
                        bufImg = ImageIO.read(Classe_Das_Imagens.getResource( listaDosArquivos.get( img_Atual ) ) );
                        icon   = new ImageIcon(bufImg);
                        image  = icon.getImage();//ImageIO.read(f);  
                    } catch (IOException ex) {}  

                    try {  
                        image = icon.getImage();//ImageIO.read(f);  
                        int widith = image.getWidth(icon.getImageObserver() ) + largura;
                        int height = image.getHeight(icon.getImageObserver() )+ altura;
                                                                        
                        lbConteudo_Online.setIcon(new ImageIcon(image.getScaledInstance(
                            widith, height, Image.SCALE_DEFAULT)));
                        
                        try{
                                                        
                            jSlider1.setMaximum (widith);  
                            //jSlider1.setMinimum  (widith/10);  
                            jSlider1.setMinimum  (0);  
                            
                            //jSlider1.setMajorTickSpacing(widith/10); 
                            //jSlider1.setMinorTickSpacing(2);                              
                            
                            //jSlider1.setPaintTrack(true);
                            //jSlider1.setPaintTicks(true);  
                            //jSlider1.setPaintLabels(true); 
                            
                        } catch (Exception ex) {}
                        
                    }catch(Exception ex){}
                    
                    //Home.jPanel4.setVisible(true);
                    int vAtual = img_Atual + 1;
                    Home.lbOk1.setText( "Exercício: " + vAtual + " de: " + qtdArquivos );
                
                    String nome = listaDosArquivos.get( img_Atual ); //System.out.println("\n\n 111 - nome - " + nome);
                    String nomeList[] = nome.split(Pattern.quote(".")); //PEGAR EXTENSÃO
                    
                    try{ nome_Arquivo = nomeList[0]; } catch (Exception ex) {} //System.out.println("\n\n 222 - nome_Arquivo - " + nome_Arquivo); 
                    
                    String nomeList2[] = nome_Arquivo.split("@");                    
                    try{ Home.resposta_correta_do_exercicio_atual = nomeList2[1]; } catch (Exception ex) {} //System.out.println("\n\n 333 - Home.resposta_correta_do_exercicio_atual - " + Home.resposta_correta_do_exercicio_atual);  
                
                }
                */
            
        } catch( Exception e ){ } //} }.start();
    }
    
}